"""remove enum from tile

Revision ID: 19e8e023f5fb
Revises: cf2e08638e84
Create Date: 2018-08-23 12:43:31.403270

"""

# revision identifiers, used by Alembic.
revision = '19e8e023f5fb'
down_revision = 'cf2e08638e84'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tile', 'status')
    op.add_column('Tile', sa.Column('status', sa.String(255), nullable=False, default="raw"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tile', sa.Column('status', sa.String(255), nullable=False, default="raw"))

    # ### end Alembic commands ###
