"""add_tile_ready

Revision ID: 423507fdb18e
Revises: 551e67316442
Create Date: 2017-08-30 01:55:48.266475

"""

# revision identifiers, used by Alembic.
revision = '423507fdb18e'
down_revision = '551e67316442'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tile', sa.Column('ready', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tile', 'ready')
    ### end Alembic commands ###
