"""lightcurve_to_npy

Revision ID: a169bf8b211d
Revises: 423507fdb18e
Create Date: 2017-09-09 22:32:17.558901

"""

# revision identifiers, used by Alembic.
revision = 'a169bf8b211d'
down_revision = '423507fdb18e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LightCurves', sa.Column('features_filename', sa.Text(), nullable=True))
    op.add_column('LightCurves', sa.Column('lc_filename', sa.Text(), nullable=True))
    op.drop_column('LightCurves', 'hdf_filename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LightCurves', sa.Column('hdf_filename', sa.TEXT(), nullable=True))
    op.drop_column('LightCurves', 'lc_filename')
    op.drop_column('LightCurves', 'features_filename')
    ### end Alembic commands ###
