"""simplyfied lc filenames

Revision ID: cf2e08638e84
Revises: a169bf8b211d
Create Date: 2017-09-10 03:15:53.894348

"""

# revision identifiers, used by Alembic.
revision = 'cf2e08638e84'
down_revision = 'a169bf8b211d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LightCurves', sa.Column('feats_filename', sa.Text(), nullable=True))
    op.add_column('LightCurves', sa.Column('obs_filename', sa.Text(), nullable=True))
    op.add_column('LightCurves', sa.Column('src_obs_counter', sa.PickleType(), nullable=True))
    op.create_unique_constraint(None, 'LightCurves', ['tile_id'])
    op.drop_column('LightCurves', 'lc_filename')
    op.drop_column('LightCurves', 'features_filename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LightCurves', sa.Column('features_filename', sa.TEXT(), nullable=True))
    op.add_column('LightCurves', sa.Column('lc_filename', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'LightCurves', type_='unique')
    op.drop_column('LightCurves', 'src_obs_counter')
    op.drop_column('LightCurves', 'obs_filename')
    op.drop_column('LightCurves', 'feats_filename')
    ### end Alembic commands ###
